# Generated by Django 4.2.7 on 2023-11-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemparatureEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('register_temperature', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
